name: Hourly Backup

on:
  schedule:
    - cron: '0 * * * *'  # каждый час
  workflow_dispatch:     # можно запустить вручную

jobs:
  backup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Установить зависимости
        run: pip install requests

      - name: Скачать и сохранить бэкап
        env:
          BACKUP_URL: ${{ secrets.BACKUP_URL }}
        run: |
          mkdir -p backups
          timestamp=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
          curl "$BACKUP_URL" > backups/backup_$timestamp.json

      - name: Коммит и пуш
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add backups/
          git commit -m "Автобэкап $timestamp" || echo "Нечего коммитить"
          git push
