name: Hourly Backup

on:
  schedule:
    - cron: '0/10 * * * *'  # каждые 10 минут
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout backups branch
        uses: actions/checkout@v3
        with:
          ref: backups
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run backup script
        env:
          BACKUP_SECRET: ${{ secrets.BACKUP_SECRET }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          mkdir -p backups
          python backup.py backups/backup.json

      - name: Commit and push backups
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add backups/backup.json
          git commit -m "Update backup" || echo "Нечего коммитить"
          git push origin backups
