name: Hourly Backup

on:
  schedule:
    - cron: '0/10 * * * *'  # каждые 10 минут
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup Python and requirements
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install requests
        run: pip install requests

      - name: run backup script
        env:
          BACKUP_URL: ${{ secrets.BACKUP_URL }}              # https://my-wishlist.onrender.com/admin/backup (GET)
          BACKUP_RECEIVE_URL: ${{ secrets.BACKUP_RECEIVE_URL }}  # https://my-wishlist.onrender.com/admin/backup?token=...
        run: |
          python backup.py

      - name: commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull --rebase
          git add backups/
          git commit -m "Autobackup $timestamp" || echo "Нечего коммитить"
          git push
